/**
 * This file is part of Shoddy Sense.
 * Copyright (C) 2007 Cathy Fitzpatrick <cathy@cathyjf.com>
 * Created in March 2007.
 *  
 * This program is free software: you can redistribute it and/or modify 
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or  
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 **/

package shoddysense;
import java.io.*;
import java.awt.image.*;
import java.util.*;
import shoddysenseserver.ImageSet;

/**
 *
 * @author  Cathy
 */
public class Board extends javax.swing.JFrame {
    
    private static final Random m_random = new Random();
    
    /** Creates new form Board */
    public Board(String imageSetFile) {
        initComponents();
        
        ImageSet images = null;
        try {
            images = new ImageSet(imageSetFile);
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage() + ": " + imageSetFile);
            return;
        }
        
        Set set = images.getFiles();
        String[] files = (String[])set.toArray(new String[set.size()]);
        String file = files[m_random.nextInt(files.length)];
        
        boolean[][] data = ImageSet.getDataFromImage(images.getImage(file));
        
        final GameBoardPanel board = new GameBoardPanel(data, new GameBoardListener() {
                public void spaceClicked(int x, int y) {
                    System.out.println(x + ", " + y);
                }
            });
        
        board.setVisible(true);
        board.setSize(200, 200);
        board.setLocation(270, 30);
        getContentPane().add(board);
            
        final ImageSet fImages = images;
        ImageSelector selector = new ImageSelector(images, new ImageSelectListener() {
                public void choseImage(ImageSelector selector, String file) {
                    board.setData(ImageSet.getDataFromImage(fImages.getImage(file)));
                    board.repaint();
                }
            });
        selector.setVisible(true);
        selector.setSize(200, 400);
        selector.setLocation(30, 30);
        getContentPane().add(selector);
        
        setSize(520, 300);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Board b = null;
                if (args.length != 0) {
                    b = new Board(args[0]);
                } else {
                    b = new Board("standard.jar");
                }
                b.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
